version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.11  # swap here for MariaDB latest stable
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnapp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
